apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/larrietacohen/argocd.git
    targetRevision: HEAD
    path: helm-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true              # elimina recursos que ya no están en Git
      selfHeal: true           # repara el estado si alguien lo modifica desde el clúster
    syncOptions:
      - CreateNamespace=true   # útil si el namespace no existe aún
